### ISSUE TITLE
fatal error on install: PHP Configuration Option 'opcache.load_comments' is unknown

### ISSUE THREAD

**Issue by iargent** [oat-sa/package-tao#23]
Installation proceeds smoothly, until I have to enter the following line:

```
sudo -u www-data php tao/scripts/taoInstall.php \
--db_driver pdo_mysql \
--db_host localhost \
--db_name taoUnitTest \
--db_user myuser \
--db_pass tao \
--module_namespace http://sample/first.rdf \
--module_url http://myurl \
--user_login admin \
--user_pass admin \
-e taoCe
```

Then I get the following message:

A fatal error occured during installation: PHP Configuration Option 'opcache.load_comments' is unknown.

I am using PHP 7.0.7-5 on Debian "testing".

Since opcache.load_comments was removed at some point before PHP 7, I tried grepping through the code to see if I could comment out a failing check. I found such a check in `vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php`, but it already seems to check for PHP7 and commenting out the exception throwing did not make any difference (lines 167 and 171).

In case it helps, here's the line I used to install the necessary dependency packages:

```
apt-get -y install unzip sudo mysql php apache2 git php-mbstring php-curl php-zip php-dom php-mysql
```

**Comment by isntall** [comment]
I was using Ubuntu 16.04 and got pretty much the same results for the install. I turned off the opcache for the install and was able to proceed. Once the install had finished, I turned on the opcache again, without ill effect.
