### ISSUE TITLE
PHP Fatal error:  Cannot use oat\taoQtiItem\model\qti\datatype\String as String because 'String' is a special class name in /var/www/html/package-tao/taoQtiItem/model/qti/datatype/String.php on line 24

### ISSUE THREAD

**Issue by MuhRizal** [oat-sa/package-tao#26]
I am using php7 in Ubuntu 16.04
Previously I have same error like https://github.com/oat-sa/package-tao/issues/23
But after I  turned off the opcache then got error after I enter following line:

sudo -u www-data php tao/scripts/taoInstall.php \
 --db_driver pdo_mysql \
 --db_host localhost \
 --db_name taodb \
 --db_user root \
 --db_pass secret \
 --module_namespace https://mywebsite/package-tao/taodb.rdf \
 --module_url https://mywebsite/package-tao \
 --user_login admin \
 --user_pass admin \
 -e taoCe

This is the error message:
* Running tao/scripts/taoInstall.php
PHP Fatal error:  Cannot use oat\taoQtiItem\model\qti\datatype\String as String because 'String' is a special class name in /var/www/html/package-tao/taoQtiItem/model/qti/datatype/String.php on line 24

any one has same error and know how to solve it?

**Comment by krampstudio** [comment]
This issue has been fixed and is available through the `develop` branch. Please checkout the branch, run a `composer udpate` and try to install again.
