### ISSUE TITLE
Skipping Question Problem

### ISSUE THREAD

**Issue by bieronym** [oat-sa/package-tao#28]
In a test after you skip a question, is it possible to see at again in the end?
Thanks

**Comment by jsconan** [comment]
As soon as you have set the navigation mode of the test part to non linear (general properties of the test part) you can freely navigate back and forward. However you are restricted by the allowed number of attempts. In that case you should also set the Max Attempts (Item Session Control settings) of each items to 0 (infinite attempts).

You may also activate the Review Screen (Test Navigation settings of section/items) to display the list of reachable items on the left side.

However if your test part is linear you cannot return to previously answered or skipped item.
