### ISSUE TITLE
Your browser does not meet the technical requirements to run TAO

### ISSUE THREAD

**Issue by mrmevlut** [oat-sa/package-tao#73]
Hello

I installed the TAO platform with ubuntu 18 and php7.2 but the page looks like this. I was getting "access denied" warning before in the URL. I've done this by setting up php7.2, but the page still looks like this.

![tao](https://user-images.githubusercontent.com/12457307/91409865-b893ab80-e84e-11ea-97f9-979a89cd5fc9.jpg)

Thank you.

**Comment by babarinde** [comment]
@mrmevlut 
For  starters it seems you are running an old version, you might want to install v3.3-rc02 instead.
[You can use this link to install](https://adminguide.taotesting.com/3.3/installation-and-upgrade/ubuntu-and-debian)

**Comment by mrmevlut** [comment]
Thank you. It's done.
